# Site settings
title: Srishti Negi 
description: Srishti Negi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Srishti Negi
user_description:  
user_title: Software Engineer
email: snegi1@hawk.iit.edu
twitter_username: 
linkedin_username: srishtinegi
github_username:  snegi11
instagram_username: #


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
